import { AppThemeProvider } from "@/contexts/theme-provider";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles } from "@/styles/global";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable}`} data-theme="dark">
      <body>
        <StyledComponentsRegistry>
          <AppThemeProvider>
            <GlobalStyles />
            {children}
          </AppThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
