import { AppThemeProvider } from "@/contexts/theme-provider";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles } from "@/styles/global";
import { theme } from "@/styles/theme";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "styled-components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable}`}
      data-theme="dark"
    >
      <body>
        <StyledComponentsRegistry>
          <AppThemeProvider>
            <GlobalStyles />
            {children}
          </AppThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
