import { MouseGlow } from "@/components/MouseGlow";
import { Navbar } from "@/components/Navbar";
import { SmoothScroll } from "@/components/SmoothScroll";
import { AppThemeProvider } from "@/contexts/theme-provider";
import type { ThemeMode } from "@/contexts/theme-provider/props";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles } from "@/styles/global";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { cookies } from "next/headers";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  const messages = await getMessages();
  const cookieStore = await cookies();
  const cookieTheme = cookieStore.get("theme")?.value;
  const initialMode: ThemeMode = cookieTheme === "light" ? "light" : "dark";

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      className={`${inter.variable}`}
      data-theme={initialMode}
    >
      <body>
        <StyledComponentsRegistry>
          <NextIntlClientProvider messages={messages}>
            <AppThemeProvider initialMode={initialMode}>
              <GlobalStyles />
              <MouseGlow />
              <Navbar />
              <SmoothScroll>
                <div className="app-shell">{children}</div>
              </SmoothScroll>
            </AppThemeProvider>
          </NextIntlClientProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
